-- Define a function to set up G-code syntax highlighting

function setup_gcode_highlight()
-- Create a new syntax group for G-code vim.cmd('syntax clear')
  vim.cmd('syntax enable')
  vim.cmd('syntax match gcodeComment ";.*$"')
  vim.cmd('syntax match gcodeA "\\vA[0-9]+"')
  vim.cmd('syntax match gcodeB "\\vB[0-9]+"')
  vim.cmd('syntax match gcodeC "\\vC[0-9]+"')
  vim.cmd('syntax match gcodeD "\\vD[0-9]+"')
  vim.cmd('syntax match gcodeE "\\vE[0-9]+"')
  vim.cmd('syntax match gcodeF "\\vF[0-9]+"')
  vim.cmd('syntax match gcodeG "\\vG[0-9]+"')
  vim.cmd('syntax match gcodeH "\\vH[0-9]+"')
  vim.cmd('syntax match gcodeI "\\vI[0-9]+"')
  vim.cmd('syntax match gcodeJ "\\vJ[0-9]+"')
  vim.cmd('syntax match gcodeK "\\vK[0-9]+"')
  vim.cmd('syntax match gcodeL "\\vL[0-9]+"')
  vim.cmd('syntax match gcodeM "\\vM[0-9]+"')
  vim.cmd('syntax match gcodeN "\\vN[0-9]+"')
  vim.cmd('syntax match gcodeP "\\vP[0-9]+"')
  vim.cmd('syntax match gcodeQ "\\vQ[0-9]+"')
  vim.cmd('syntax match gcodeR "\\vR[0-9]+"')
  vim.cmd('syntax match gcodeS "\\vS[0-9]+"')
  vim.cmd('syntax match gcodeT "\\vT[0-9]+"')
  vim.cmd('syntax match gcodeX "\\vX[0-9]+\\.[0-9]+"')
  vim.cmd('syntax match gcodeY "\\vY[0-9]+\\.[0-9]+"')
  vim.cmd('syntax match gcodeZ "\\vZ[0-9]+\\.[0-9]+"')
  -- Link the syntax groups to highlight groups
  vim.cmd('highlight link gcodeG Keyword')
  vim.cmd('highlight link gcodeM Function')
  vim.cmd('highlight gcodeT guifg=Orange')
  vim.cmd('highlight gcodeX guifg=Green')
  vim.cmd('highlight gcodeY guifg=Red')
  vim.cmd('highlight gcodeZ guifg=Blue')
  vim.cmd('highlight link gcodeComment Comment')
end

