require('me')
require('config.lazy')

require('config.auto_session')
require('config.chatgpt')
require('config.fugitive')
require('config.gitsigns')
require('config.lsp_zero')
require('config.lualine')
require('config.ror')
require('config.rose_pine')
require('config.shade')
require('config.telescope')
require('config.terminal')
require('config.treesitter')
